[package]
name = "venix"
version = "1.0.0"
edition = "2024"
description = "A high-performance, archetype-based ECS engine written in Rust."
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["ecs", "archetype", "simulation", "parallel"]
categories = ["game-engines", "development-tools"]

[dependencies]
rayon = "1.12.0"

[lib]
name = "venix"
path = "src/lib.rs"

[[test]]
name = "tests"
path = "tests/ecs_tests.rs"
