[package]
name = "venix"
version = "2.1.1"
edition = "2024"
description = "A high-performance, archetype-based ECS engine written in Rust."
readme = "README.md"
repository = "https://github.com/ArjitSinghLodhi/Venix"
license = "MIT OR Apache-2.0"
keywords = ["ecs", "archetype", "simulation", "parallel"]
categories = ["game-engines", "development-tools"]

[dependencies]
venix_macros = { version = "1.0.4", optional = true }
fxhash = "0.2.1"
indexmap = "2.14.0"
rayon = "1.12.0"
orx-concurrent-bag = "4.0.1"
papaya = "0.2.5"

[dev-dependencies]
rusty-fork = "0.3.1"

[lib]
name = "venix"
path = "src/lib.rs"

[[test]]
name = "ecs_tests"
path = "tests/ecs_tests.rs"

[[test]]
name = "event_tests"
path = "tests/event_tests.rs"

[[test]]
name = "derive_test"
path = "tests/derive_tests.rs"
required-features = ["derive"]

[[test]]
name = "change_track_test"
path = "tests/changed_tracking_test.rs"
required-features = ["reactivity"]

[[test]]
name = "added_tracking_test"
path = "tests/added_tracking_test.rs"
required-features = ["reactivity"]

[features]
default = []
derive = ["dep:venix_macros"]
reactivity = []
